services:
  custardbot:
    image: succulentgoose/custardbot:latest
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - TOKEN
      - CLIENT_ID
      - GUILD_ID
